version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: cabryder.local

    volumes:
      - ./dist/cabryder/browser:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
